# Generated by Django 5.0.2 on 2024-02-09 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.FloatField()),
                ('category', models.CharField(choices=[('FBO', 'F_books'), ('FAC', 'F_accessory'), ('FPR', 'F_Perfume'), ('FBP', 'F_beauty products'), ('MAC', 'M_accessory'), ('MBO', 'M_books'), ('MPR', 'M_Perfume'), ('MFT', 'M_fitness')], max_length=3)),
                ('product_imge', models.ImageField(upload_to='Product')),
            ],
        ),
    ]
