# Generated by Django 5.0.2 on 2024-02-09 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('FBO', 'F_books'), ('FAC', 'F_accessory'), ('FSC', 'F_skinCare'), ('FBP', 'F_beauty_products'), ('MAC', 'M_accessory'), ('MBO', 'M_books'), ('MTO', 'M_Tool'), ('MFT', 'M_fitness')], max_length=3),
        ),
    ]
