# Generated by Django 5.0.2 on 2024-02-22 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_wishlist_products_wishlist_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
