# Generated by Django 5.0.2 on 2024-02-22 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_delete_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
