# Generated by Django 5.0.2 on 2024-02-23 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_wishlist_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='wishlist',
            unique_together=set(),
        ),
    ]
