# Generated by Django 5.0.2 on 2024-02-26 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_wishlist_unique_together'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
