# Generated by Django 5.0.2 on 2024-02-26 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_contactmessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactMessage',
        ),
    ]
